matrix:
  include:
  - language: node_js
    node_js: '8'
    script:
    - npm run flow
    - npm run lint
    - npm test
    cache:
      directories:
      - node_modules
  - language: objective-c
    os: osx
    osx_image: xcode9.1
    before_install:
    - brew install watchman
    install:
    - npm install
    script:
    - xcodebuild -sdk iphoneos10.0 -project ios/tapsafe.xcodeproj -scheme tapsafe -configuration Release build -archivePath tapsafe.xcarchive' archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    cache:
      directories:
      - node_modules
  - language: android
    before_install:
    - nvm install 8
    install:
    - npm install
    android:
      components:
      - build-tools-23.0.1
      - android-23
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
    script:
    - cd android && ./gradlew assembleRelease
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - node_modules
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
