matrix:
  include:
  - language: node_js
    node_js: '8'
    script:
    - npm run flow
    - npm test
    cache:
      directories:
      - node_modules
  - language: objective-c
    os: osx
    osx_image: xcode9.1
    before_install:
    - brew install watchman
    install:
    - npm install
    script:
    - xcodebuild build -sdk -project ios/tapsafe.xcodeproj -scheme tapsafeTests CODE_SIGNING_REQUIRED=NO
    cache:
      directories:
      - node_modules
  - language: android
    before_install:
    - nvm install 8
    install:
    - npm install
    - npm install -g react-native-cli
    android:
      components:
      - build-tools-23.0.1
      - android-23
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
    script:
    - cd android && ./gradlew assembleRelease
    cache:
      directories:
      - node_modules
