matrix:
  include:
  - language: node_js
    node_js: '6'
    install:
    - npm install
    script:
    - npm run flow
    - npm test
    cache:
      directories:
      - node_modules
  - language: objective-c
    os: osx
    osx_image: xcode9.1
    xcode_project: ios/tapsafe.xcodeproj
    xcode_scheme: tapsafeTests
    before_install:
    - brew install node
    - brew install watchman
    install:
    - npm install
    cache:
      directories:
      - node_modules
  - language: android
    before_install:
    - nvm install 6
    install:
    - npm install
    - npm install -g react-native-cli
    android:
      components:
      - build-tools-23.0.1
      - android-23
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
    script:
    - cd android && ./gradlew assembleRelease
